### ISSUE TITLE
Module Scaffold error

### ISSUE THREAD

**Issue by xLink** [AsgardCms/Platform#23]
Just trying to create a module and it errored out 

``` bash
 $ art asgard:scaffold
Please enter the module name. Example: vendor/name. xlink/faq
Do you want to use Eloquent or Doctrine ? [eloquent]
  [0] Eloquent
  [1] Doctrine
 > 0
Enter entity name. Leaving option empty will continue script. Faq
Enter entity name. Leaving option empty will continue script.
Enter value object name. Leaving option empty will continue script.
exception 'ErrorException' with message 'file_put_contents(/Faq/Providers/FaqServiceProvider.php): failed to open stream: No such file or directory' in /Users/danaldridge/Sites/portfolio/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:74
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/Users/danaldri...', 74, Array)
#1 /Users/danaldridge/Sites/portfolio/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(74): file_put_contents('/Faq/Providers/...', '<?php namespace...', 0)
#2 /Users/danaldridge/Sites/portfolio/Modules/Workshop/Scaffold/Generators/Generator.php(93): Illuminate\Filesystem\Filesystem->put('/Faq/Providers/...', '<?php namespace...')
#3 /Users/danaldridge/Sites/portfolio/Modules/Workshop/Scaffold/Generators/FilesGenerator.php(30): Modules\Workshop\Scaffold\Generators\Generator->writeFile('/Faq/Providers/...', '<?php namespace...')
#4 /Users/danaldridge/Sites/portfolio/Modules/Workshop/Scaffold/ModuleScaffold.php(101): Modules\Workshop\Scaffold\Generators\FilesGenerator->generateModuleProvider()
#5 /Users/danaldridge/Sites/portfolio/Modules/Workshop/Console/ScaffoldCommand.php(52): Modules\Workshop\Scaffold\ModuleScaffold->scaffold()
#6 [internal function]: Modules\Workshop\Console\ScaffoldCommand->fire()
#7 /Users/danaldridge/Sites/portfolio/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#8 /Users/danaldridge/Sites/portfolio/vendor/laravel/framework/src/Illuminate/Console/Command.php(115): Illuminate\Container\Container->call(Array)
#9 /Users/danaldridge/Sites/portfolio/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /Users/danaldridge/Sites/portfolio/vendor/laravel/framework/src/Illuminate/Console/Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /Users/danaldridge/Sites/portfolio/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /Users/danaldridge/Sites/portfolio/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Modules\Workshop\Console\ScaffoldCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /Users/danaldridge/Sites/portfolio/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /Users/danaldridge/Sites/portfolio/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(91): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /Users/danaldridge/Sites/portfolio/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 {main}
```

**Comment by bradxxx** [comment]
what should be the value for entities? i am getting pass through this step on making new module

**Comment by nWidart** [comment]
The names of entities you want to create.
In laravel 'terms' an entity = a model.

So if you're creating a Recipe module, you could create:
- Recipe
- Category

For instance.

**Comment by bradxxx** [comment]
i am skipping it by just pressing enter. but it is again asking the same for entity

**Comment by nWidart** [comment]
You can leave empty 2 times to get out.

**Comment by bradxxx** [comment]
its just giving me this
"[ERROR] A value is required."

**Comment by nWidart** [comment]
Did you run a composer update ?

**Comment by bradxxx** [comment]
i just install it by running composer & the backend panel is already showing up. 
Do i have to run it again?

**Comment by nWidart** [comment]
In the admin , go to the Modules link, and make sure you're on 1.0.4.

**Comment by bradxxx** [comment]
no.. it says  version 1.0 beta
Do i have to run composer again?

**Comment by nWidart** [comment]
I mean here :

![screen shot 2015-06-11 at 6 49 36 pm](https://cloud.githubusercontent.com/assets/882397/8112821/af0ef338-106a-11e5-971c-51a35350126a.png)


Not in the footer.

**Comment by bradxxx** [comment]
Pls see this
![admin](https://cloud.githubusercontent.com/assets/10245980/8112904/9ad089e8-108a-11e5-99f9-cd0091dde038.png)

**Comment by nWidart** [comment]
Ok this means you're still on an old version. You need to run composer update.

**Comment by bradxxx** [comment]
After composer update it working now. Thanks

**Comment by nWidart** [comment]
Awesome :+1:
