### ISSUE TITLE
Laravel 5.8

### ISSUE THREAD

**Issue by LarryTX** [AsgardCms/Platform#688]
Laravel is now at ver. 5.8 (stable), but AsgardCMS seems stuck at 5.5.*. Is there a timeline/roadmap for upgrading to the latest version of Laravel? It seems that AsgardCMS is getting way behind, and we'll lose the ability to use many packages as they move ahead.

**Comment by linhtinh92** [comment]
You can clone from branch master, asgard use laravel ver 5.7

**Comment by LarryTX** [comment]
@linhtinh92 I'm afraid that I don't understand. Branch Master has in it's composer.json, `"laravel/framework": "5.5.*",`, which would prevent it from upgrading the laravel framework to anything above 5.5. Are you suggesting that a different version of the laravel/framework dependency be specified? If I do that, how will it work with the other dependencies? Most of the major modules seem to be idavoli packages, and idavoli does not seem to specify any laravel version as a dependency, so I assume it work work.

That being the case, wouldn't it work to just change the laravel/framework version in my current version rather than cloning the Master branch? I've begun adding modules and a "backend" theme to my current installation. To have to redo all that stuff every time a new version of Laravel comes out would be laborious.

It would seem that Asgard anticipated so many user needs in designing the CMS except for the most basic: How to keep up-to-date with the underlying framework. This has major implications as the Laravel framework makes changes to accommodate changing security needs.

**Comment by mikemand** [comment]
Branch [master](https://github.com/AsgardCms/Platform/tree/master) (which can be installed by specifying version `4.0-dev` when you install) is currently running on [Laravel 5.7](https://github.com/AsgardCms/Platform/blob/6e778d289fcb0030ee7963fa8ef998963422dd3a/composer.json#L16).

It has not been updated to Laravel 5.8, as of yet, because I think we are waiting for a couple more packages to update (I could be wrong; it's been almost a week since I last checked).

**Comment by LarryTX** [comment]
Actually, 4.0-dev can't be found by composer. Here's what I get:
```
D:\xampp\htdocs>composer create-project asgardcms/platform:4.0-dev memehope


  [InvalidArgumentException]
  Could not find package asgardcms/platform with version 4.0-dev.


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]
```

**Comment by mikemand** [comment]
Hi @LarryTX,

Sorry, the composer command would be:

```sh
composer create-project --stability dev asgardcms/platform <projectname>
```

It looks like there's a [security advisory](https://github.com/FriendsOfPHP/security-advisories/blob/master/league/commonmark/2019-03-21.yaml) problem with the version of markdown parser we have configured. I will take a look and see what needs to be done to fix that.

**Comment by mikemand** [comment]
PR opened for the security issue: #689

**Comment by LarryTX** [comment]
Actually, it should be asgardcms/platform:4.0.x-dev; the .x is essential. Unfortunately, the dev branch seems to be unusable at this point. Going to /en/backend throws  stream of error messages about certain .js files not being found. I started trying to cure those errors, but indeed the files in question don't seem to be there and seem to be essential. Looks like the only resolution is simply to drop Asgard until it catches up with Laravel.

**Comment by motchju** [comment]
Hello for the missing file please do a npm run prod

**Comment by LarryTX** [comment]
@motchju, that didn't improve matters. I ran `npm run prod`. By the way, why `prod` instead of `dev`?  The specific error that I'm getting is:
```
 ErrorException (E_ERROR)
Unable to locate Mix file: /js/manifest.js. (View: D:\xampp\htdocs\memehope\Themes\Adminlte\views\layouts\master.blade.php) (View: D:\xampp\htdocs\memehope\Themes\Adminlte\views\layouts\master.blade.php)
```
and
```
"Unable to locate Mix file: /js/manifest.js. (View: D:\xampp\htdocs\memehope\Themes\Adminlte\views\layouts\master.blade.php) (View: D:\xampp\htdocs\memehope\Themes\Adminlte\views\layouts\master.blade.php) ◀"
```
The error originates at lines 95-97 of /Themes/Adminlte/views/layouts/master-blade.php:
```
<script src="{{ mix('js/manifest.js') }}"></script>
<script src="{{ mix('js/vendor.js') }}"></script>
<script src="{{ mix('js/app.js') }}"></script>
```
of these, I cannot find manifest.js or vendor.js anywhere. The themes webpack.mix.js has tons of lines commented out, but even looking at them, there's nothing that would create either one of the two missing js files. Even in terms of cache, the only components listed in mix-manifest.json are:
```
{
    "/assets/css/asgard.css": "/assets/css/asgard.css",
    "/assets/js/main.js": "/assets/js/main.js"
}
```
Looking at the project root webpack.min.js, ESLint hates you (or me). It's giving a ton of messages all of which say `Expected linebreaks to be 'LF' but found 'CRLF`. but I don't see where that would lead to any of these problems. And it doesn't appear to produce a manifest.js or vendor.js.

**Comment by mikemand** [comment]
@LarryTX I'm not sure exactly where your `webpack.mix.js` file came from, but [the one on master](https://github.com/AsgardCms/Platform/blob/58c97536229c398aaf210b8bc7b7d3c93c9c2dd9/webpack.mix.js) doesn't have a whole bunch of stuff commented out.

The error is because for some reason Mix didn't extract the vendor packages (that's what `vendor.js` is for, and `manifest.js` just lets the browser know to load `vendor.js` first and tells it how things are linked between `vendor.js` and `app.js`). Other than running `npm install` and `npm run dev` (or `npm run prod` whichever you want...`prod` will minify and uglify the assets, whereas `dev` will not), I cannot think of any reason why Mix wouldn't have run the `.extract(...)` portion of its file.

**Comment by LarryTX** [comment]
I finally seem to have gotten it to work by creating an entirely new project (the third one) and running back through everything again. Maybe it was just a hiccup on the old projects. Now, I'm back to Issue #687. I've got a project, but I can't do anything with it because I'm unable to set permissions. And roles. And users. And Just about anything. On the roles page, just a spinning circle. Most other admin pages also. Let it spin overnight because I forgot to shut it down. It was still spinning in the morning when I woke up.

**Comment by mikemand** [comment]
Open the developer tools and check the console:

1. Right-click -> Inspect
1. Click on "Console"
1. Refresh the page (Chrome, and I assume other browsers, doesn't show the full error when you open the console and the error has already occurred)
1. Copy and paste or screenshot the errors and put them here

Most likely the problem is because one of the scripts failed to load or had an error while it was running. This is the biggest problem with using JavaScript (Vue, React, Angular, whatever - they all have this problem). If one part of the script errors and the rest of the script can't continue you get a completely broken page because then NO scripts can run.

**Comment by LarryTX** [comment]
You are so totally kind and patient. I truly hope this somehow makes the whole development process easier and better for you. Here's what the Firefox console says:
```
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools vendor.js:26300:47
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html vendor.js:26309:45
Unhandled promise rejection Error: "Request failed with status code 403"

    createError https://test.lcl/js/app.js:26064 settle https://test.lcl/js/app.js:80829 handleLoad https://test.lcl/js/app.js:25938 

app.js:29510:11
Source map error: request failed with status 404
Resource URL: https://test.lcl/js/vendor.js
Source Map URL: index.js.map[Learn More]
```
If you need me to run it in Chrome, I can do that. Looking at that 403 error, I should say that, much earlier, I did try clicking the New Role button. I promptly received a notification that that was unauthorized. I checked in the db tables. role_users shows my logged in user as being an Admin, a role that is in users.

**Comment by mikemand** [comment]
Hi Larry,

Thank you for your kind words.

With that 403 error, I'm wondering if you have an API key for your user. There *was* a bug for a while where newly created users did not have an API key generated automatically, but I thought that was fixed.

Would you mind checking either the API Keys page or your database in the `user_tokens` table for your user?

I am not really sure why you're having so much trouble, and I'm very sorry that you are. I have two sites running on Asgard v4 right now, and the only difference I can see between us is you used Composer to create your project whereas I cloned the repository. If this is the root of the problem, I would say there is something being ignored by Composer that we need, but I have no idea what.

**Comment by LarryTX** [comment]
Hi mikemand, You may have something on this API Key thing. I've gotten several messages abut no API Key being set, and I always went to the App Key which was generated by Artisan. Didn't know anything about the User API Key. (I'm going to have to do some studying obviously.) Anyway, when I went looking, there is definitely an API Key in the table user_tokens, but when I pull up the /backend/account/api-keys page, it shows no tokens. I made screenshots for our edification.

Just for grins, I clicked **Generate new API key**. It looked like it was doing that, but at the end, I got a "Unauthorized" notification. Landed on the dashboard. When I went back to the API Keys page there were no keys listed. In addition, in the database, there was no new row in user_tokens. (I'm not sure where a new key is created or an old key is updated in this process, but it doesn't look like either happened.) Also, the endless gyrating circle/wait signal remains the same on the Roles page. (By the way, the logged in user is ID 2.)

![Asgard API Keys page](https://user-images.githubusercontent.com/20743/54870482-0b715580-4d75-11e9-9d4e-a841af01ef53.png)
![Asgard User Token](https://user-images.githubusercontent.com/20743/54870489-2cd24180-4d75-11e9-8804-070e016ae4b7.png)

**Comment by LarryTX** [comment]
For what it's worth, I attempted to clone the master branch since you said that you'd had no problems with it. Cloning, npm install and npm run dev all went without a hitch. However, when I attempted to run php artisan asgard:install, it bombed like this:
```
D:\xampp\htdocs\asgard-clone>php artisan asgard:install
PHP Warning:  require(D:\xampp\htdocs\asgard-clone/vendor/autoload.php): failed to open stream: No such file or directory in D:\xampp\htdocs\asgard-clone\artisan on line 18

Warning: require(D:\xampp\htdocs\asgard-clone/vendor/autoload.php): failed to open stream: No such file or directory in D:\xampp\htdocs\asgard-clone\artisan on line 18
PHP Fatal error:  require(): Failed opening required 'D:\xampp\htdocs\asgard-clone/vendor/autoload.php' (include_path='D:\xampp\php\PEAR') in D:\xampp\htdocs\asgard-clone\artisan on line 18

Fatal error: require(): Failed opening required 'D:\xampp\htdocs\asgard-clone/vendor/autoload.php' (include_path='D:\xampp\php\PEAR') in D:\xampp\htdocs\asgard-clone\artisan on line 18
```
In the cloned version, there is not vendor directory. (There is in all the composer installs.)

There isn't a vendor directory in the github master branch, which of course doesn't mean much because it could be created by some process. Looking over the commit notes, I saw that babelrc was responsible for extracting a number of vendor packages. I have babel and its subordinate packages installed globally, so I decided to try installing them locally and running npm install and npm run dev again. That of course didn't help.

There doesn't appear to be anything in package.json, webpack.mix.js or babelrc that would create a vendor directory, and it just isn't there in the master branch.

**Comment by mikemand** [comment]
Hi Larry,

When you clone the repository, you have to run `composer install` manually. Usually `composer create-project` would take care of this for you automatically, but cloning the repository only supplies the bare necessities.

**Comment by LarryTX** [comment]
Thanks for your patience! As you can probably tell, I’m used to installing things through composer, although I do maintain my own repositories.  Unfortunately, `composer install` fails. Not sure if its because of everything I've done before. Here's what it gives me:
```
D:\xampp\htdocs\asgard-clone>composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - roave/security-advisories dev-master conflicts with league/commonmark[0.15.4].
    - roave/security-advisories dev-master conflicts with league/commonmark[0.15.5].
    - roave/security-advisories dev-master conflicts with league/commonmark[0.15.6].
    - roave/security-advisories dev-master conflicts with league/commonmark[0.15.7].
    - Installation request for roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master].
    - Installation request for league/commonmark ^0.15.4 -> satisfiable by league/commonmark[0.15.4, 0.15.5, 0.15.6, 0.15.7].
```
Should I start with a fresh clone, or is this an different impediment.?

**Comment by mikemand** [comment]
Hi Larry,

That is the security issue I was referring to yesterday. I fixed it in PR #689.

If you wouldn't mind starting from a fresh clone, that should fix this. `master` is currently at 58c97536229c398aaf210b8bc7b7d3c93c9c2dd9.

**Comment by LarryTX** [comment]
Now you got me. I tried cloning the master and got the roave/security-advisories conflicts with league/commonmark conflicts. Then tried to clone from the pull request. (Not really sure of the correct way.) Nothing I tried seemed to work. No matter what I did, it wasn’t found in the upstream origin. Can you give me a little help here on how to clone this pull request?

Larry E. Lutz

**Comment by LarryTX** [comment]
Did a fresh clone from master. That fixed the security issues. Now, the clone is giving me the same issues as the composer install:

- On the /en/backend/user/users and the /en/backend/user/roles pages, I have an endless circular wait symbol in the data area for each and in the topnav.
- If I click the button on either to create a new user or role, I get an Unauthorized message and get promptly bumped back to the Dashboard.
- On /en/backend/account/api-keys, the data area is blank.
- The access_token column in the user_tokens table in the database contains an entry.
- If I click the button on the API Keys page to generate a new API Key, I receive the same Unauthorized message that I get on the Users and Roles pages.
- Checking the role_users table, my logged in user is related to the admin role.

So we're back to where we were before we started on the cloning journey. This issue doesn't appear to be related to composer.

I've never had this happen before, so I'm kind of at a loss to know where to start. I have limited experience with Laravel, but I have years of working with YII/Yii2 and a considerable amount working with CakePHP. Here is some of the information that could present an issue (although I'm at a loss to see how):
- Operating System: Windows 10 Pro
- Web server: Apache 2.4
- Database: MySQL 8.0.15
- PHP version: 7.2.10
- This could be an issue. The website is set up as a virtualhost SSL (https) site. My other virtualhosts setup exactly as this one is work perfectly fine.

If your need any other information, just let me know.

**Comment by mikemand** [comment]
Hi Larry,

Your log from `/storage/logs` shows an error relating to cache. This would definitely account for the `Unauthorized` error, even though you have an API key. Maybe Laravel changed something behind the scenes in 5.7 relating to cache that I didn't catch?

How do you have cache set up? Your `.env` file by default will say something like `CACHE_DRIVER=array` and `TRANSLATIONS_CACHE_DRIVER=file`. If either of these are set to `file`, try `array` instead. [Cache tags are not supported in `file` and `database` drivers.](https://laravel.com/docs/5.7/cache#cache-tags) (I will PR an update to the default `TRANSLATIONS_CACHE_DRIVER` so it doesn't try file anymore.)

**Comment by LarryTX** [comment]
I didn’t make any changes; just accepted the defaults. I will try changing  TRANSLATIONS_CACHE_DRIVER=file to array and let you know.

Larry E. Lutz

**Comment by LarryTX** [comment]
With that change, TRANSLATIONS_CACHE_DRIVER=array,  suddenly, we no long have a web page. It simply gives me a directory listing. And not the director listed in the vhost for this website. It show the index of the entire htdocs folder. That generally means a really serious error.

Larry E. Lutz

From: Larry Lutz
Sent: Sunday, March 24, 2019 12:55 PM
To: 'AsgardCms/Platform' <reply@reply.github.com>
Subject: RE: [AsgardCms/Platform] Laravel 5.8 (#688)

I didn’t make any changes; just accepted the defaults. I will try changing  TRANSLATIONS_CACHE_DRIVER=file to array and let you know.

Larry E. Lutz

**Comment by LarryTX** [comment]
I never use Docker, for any reason. I do have Redis, but I'm not using it at this point.

**Comment by mikemand** [comment]
Hi Larry,

At this point, I'm all out of ideas. I don't use Windows or Apache at all, so it could be any number of things I'm not aware of. Hopefully, someone else has an idea for something I haven't had you try yet.

I'm sorry I couldn't help you get this solved. 😞

**Comment by LarryTX** [comment]
Here’s the Apache error log relevant entries:

[Sun Mar 24 10:39:11.616910 2019] [php7:error] [pid 2208:tid 2064] [client 127.0.0.1:60191] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.500] not found. in D:\\xampp\\htdocs\\asgard-clone\\vendor\\laravel\\framework\\src\\Illuminate\\View\\FileViewFinder.php:137\nStack trace:\n#0 D:\\xampp\\htdocs\\asgard-clone\\vendor\\laravel\\framework\\src\\Illuminate\\View\\FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.500', Array)\n#1 D:\\xampp\\htdocs\\asgard-clone\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Factory.php(130): Illuminate\\View\\FileViewFinder->find('errors.500')\n#2 D:\\xampp\\htdocs\\asgard-clone\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ResponseFactory.php(81): Illuminate\\View\\Factory->make('errors.500', Array)\n#3 D:\\xampp\\htdocs\\asgard-clone\\app\\Exceptions\\Handler.php(80): Illuminate\\Routing\\ResponseFactory->view('errors.500', Array, 500)\n#4 D:\\xampp\\htdocs\\asgard-clone\\app\\Exceptions\\Handler.php(64): App\\Exceptions\\Handler->handleExceptions(Object(InvalidArgumentException))\n#5 D:\\xampp\\htdocs\\asgard-clone\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions in D:\\xampp\\htdocs\\asgard-clone\\vendor\\laravel\\framework\\src\\Illuminate\\View\\FileViewFinder.php on line 137, referer: https://test.lcl/en/backend/user/roles
[Sun Mar 24 10:39:11.637911 2019] [php7:error] [pid 2208:tid 2064] [client 127.0.0.1:60191] PHP Fatal error:  Uncaught InvalidArgumentException: View [errors.500] not found. in D:\\xampp\\htdocs\\asgard-clone\\vendor\\laravel\\framework\\src\\Illuminate\\View\\FileViewFinder.php:137\nStack trace:\n#0 D:\\xampp\\htdocs\\asgard-clone\\vendor\\laravel\\framework\\src\\Illuminate\\View\\FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('errors.500', Array)\n#1 D:\\xampp\\htdocs\\asgard-clone\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Factory.php(130): Illuminate\\View\\FileViewFinder->find('errors.500')\n#2 D:\\xampp\\htdocs\\asgard-clone\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ResponseFactory.php(81): Illuminate\\View\\Factory->make('errors.500', Array)\n#3 D:\\xampp\\htdocs\\asgard-clone\\app\\Exceptions\\Handler.php(80): Illuminate\\Routing\\ResponseFactory->view('errors.500', Array, 500)\n#4 D:\\xampp\\htdocs\\asgard-clone\\app\\Exceptions\\Handler.php(64): App\\Exceptions\\Handler->handleExceptions(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#5 D:\\xampp\\htdocs\\asgard-clone\\vendor\\laravel\\framework\\src\\Illuminate\\Foundati in D:\\xampp\\htdocs\\asgard-clone\\vendor\\laravel\\framework\\src\\Illuminate\\View\\FileViewFinder.php on line 137, referer: https://test.lcl/en/backend/user/roles

Larry E. Lutz

From: Larry Lutz
Sent: Sunday, March 24, 2019 1:07 PM
To: 'AsgardCms/Platform' <reply@reply.github.com>
Subject: RE: [AsgardCms/Platform] Laravel 5.8 (#688)

With that change, TRANSLATIONS_CACHE_DRIVER=array,  suddenly, we no long have a web page. It simply gives me a directory listing. And not the director listed in the vhost for this website. It show the index of the entire htdocs folder. That generally means a really serious error.

Larry E. Lutz

From: Larry Lutz
Sent: Sunday, March 24, 2019 12:55 PM
To: 'AsgardCms/Platform' <reply@reply.github.com>
Subject: RE: [AsgardCms/Platform] Laravel 5.8 (#688)

I didn’t make any changes; just accepted the defaults. I will try changing  TRANSLATIONS_CACHE_DRIVER=file to array and let you know.

Larry E. Lutz

**Comment by LarryTX** [comment]
I just sent you the Apache error log. At this point, I think I’m going back to Yii2/3. I promised myself that I’d stick it out until I could get Laravel to work, but I have to say, Laravel (not just Asgard) seems to fall flat on its face every time that I try to do something that, in Yii, would be rated at moderate, not advanced. I can’t find any way to do the advanced Yii stuff in Laravel. I have misgivings about Yii since it is Russian-dominated at the very time we in America are so very concerned about Russian interference in our elections using Web technology. Since Yii2 is busy working on 3.0 to replace Yii2, I thought it would be a good time to work on something else rather than learning 3.0. It just doesn’t seem like Laravel is ready.

Larry E. Lutz

**Comment by arturmamedov** [comment]
> 
> I just sent you the Apache error log. At this point, I think I’m going back to Yii2/3. I promised myself that I’d stick it out until I could get Laravel to work, but I have to say, Laravel (not just Asgard) seems to fall flat on its face every time that I try to do something that, in Yii, would be rated at moderate, not advanced. I can’t find any way to do the advanced Yii stuff in Laravel. I have misgivings about Yii since it is Russian-dominated at the very time we in America are so very concerned about Russian interference in our elections using Web technology. Since Yii2 is busy working on 3.0 to replace Yii2, I thought it would be a good time to work on something else rather than learning 3.0. It just doesn’t seem like Laravel is ready.

It sad that u yhink so, Laravel is a freat tool, a great framework, just try to use a stable version of AsgardCMS and u get all things work! 
And also take present that AsgardCMS Architecture is very complete and it try to separate Framework staff from the Application for realize a IoC (Inversion of Control) if it necessary, it apply a Repository Design Pattarn and Services. 
So if you only want to learn Laravel, begin with a simple project and Laravel documentation that is very simple and complete, for very fast start believe me!

**Comment by LarryTX** [comment]
Sorry @arturmamedov, between March and July, I have moved back to Yii2 and am busily creating new things. That's sort of the problem with some of your recommendations. I had completed many of the tutorials that you mentioned. I really put myself into learning Laravel and, in the process built many of the websites in the tutorials. However, when I sit down to put Laravel to work in the real world, I deal with some very complex websites. (Actually, Laravel's native ability to handle polymorphic relations was one thing that really appealed to me. Yii2's commitment to ActiveRecord means that polymorphic relations means that polymorphic relations are contrived and an add-on. Of course, that may change with Yii 3 which is coming along very nicely with a full-time developer and countless volunteers.

Unfortunately, the Laravel approach to things seems to be, "Just learn how to do what Laravel can do in the Laravel way. Trust me, you'll be happy." Therein lies my problem. I'm no at all interested in "what Laravel can do." I start from a design and find software that will enable me to build the design. Thus, far, Yii has always been able to do that. I just don't have the time to spend three months to figure out whether Laravel can do that. I even spent the time to revise my database for one site, all the over 300 normalized tables in the database, just to take advantage of Laravel's ability  to handle polymorphic relations.

Then, I ran into all kinds of problems with Laravel and AsgardCMS (mostly with Laravel itself, since I latched onto AsgardCMS to try to do some things that I couldn't make work in Laravel alone). If you look at the issue-dialog above, you can see that there were things that even the "experts" couldn't resolve. Laravel still intrigues me. I won't say that I'll never go back to it again. But I will say that I'll wait until Laravel gets more mature. (Certainly until it can handle the totallyy common, ubiquitous master/detail, multi-model forms. I became to tired of being told that "No one needs those. They're stupid." (Order/Items, Patient/Medications, etc., etc., anyone?)) Maybe later, also, when I have much, much more time. Perhaps after I retire.
